Fix #15110 - TypeError e.preventDefaulut is not a function
Fixes: #15110
Introduced by 487e1a8fa1e2b9fb30b64e3cf82e96196f5ce39e

Signed-off-by: William Desportes <williamdes@wdes.fr>