export default value vars type
Fatal error: Uncaught TypeError: Argument 13 passed to PhpMyAdmin\Export::exportTable() must be of the type string, integer given, called in \myadmin\export.php on line 566 and defined in \myadmin\libraries\classes\Export.php:893

limit_to and limit_from require string in Export class

Signed-off-by: Vitalii Tverdokhlib <vitaliytv@nitralabs.com>