Fix TypeError in Util class
TypeError: str_replace() expects parameter 3 to be string or array, int given

Signed-off-by: Maurício Meneghini Fauth <mauricio@fauth.dev>